compile2: 
	g++ -std=c++11 task2.cpp functions.cpp -larmadillo -o task2

compile3: 
	g++ -std=c++11 task3.cpp functions.cpp -larmadillo -o task3

compile4:
	g++ -std=c++11 task4.cpp functions.cpp -larmadillo -o task4

compile5:
	g++ -std=c++11 task5.cpp functions.cpp -larmadillo -o task5

compile6:
	g++ -std=c++11 task6.cpp functions.cpp -larmadillo -o task6
