test1:
	g++ test.cpp ising.cpp -o test -larmadillo -std=c++11


task4M:
	g++ task4.cpp ising.cpp -o task4 -larmadillo -std=c++11 -O3


task5M:
	g++ task5.cpp ising.cpp -o task5 -larmadillo -std=c++11 -O2
task6M:
	g++ task6.cpp ising.cpp -o task6 -larmadillo -std=c++11 -O2

task8M:
	g++ -O3 task8.cpp ising.cpp -o task8 -larmadillo -std=c++11
task8M-omp:
	g++ -O3 -fopenmp task8.cpp ising.cpp -o task8-omp -larmadillo -std=c++11



